return {
	-- {
	-- 	"mfussenegger/nvim-dap",
	-- 	config = function()
	-- 		local dap = require("dap")
	--
	-- 		dap.adapters.coreclr = {
	-- 			type = "executable",
	-- 			command = "/home/shpsyte/.local/share/nvim/mason/bin/netcoredbg",
	-- 			args = { "--interpreter=vscode" },
	-- 		}
	--
	-- 		dap.configurations.cs = {
	-- 			{
	-- 				type = "coreclr",
	-- 				name = "launch - netcoredbg",
	-- 				request = "launch",
	-- 				program = function()
	-- 					return vim.fn.input("Path to dll", vim.fn.getcwd() .. "/src/", "file")
	-- 				end,
	-- 				-- args = { "--urls", "http://localhost:5191" },
	-- 				env = {
	-- 					ASPNETCORE_ENVIRONMENT = "Development", -- Define o ambiente como Development
	-- 				},
	-- 			},
	-- 		}
	-- 	end,
	-- },
}
